
import Head from "next/head";
import React, { useState, useEffect } from "react";
import Header from "../components/header";
import InviteBanner from "../components/inviteBanner";
import ProductList from "../components/productList";
import styles from "../styles/Home.module.css";
import { requestProducts } from "../redux/slices/productSlice";
import store from "../redux/configureStore";

export const appContext = React.createContext();

export default function Home() {
  const [appState, setState] = useState({
    products: [],
  });
  useEffect(init, []);

  function init() {
    store.dispatch(requestProducts());
  }
  return (
    <div className={styles.container}>
      <appContext.Provider value={{ appState, setState }}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
        <InviteBanner />
        <ProductList products={appState.products} />
      </appContext.Provider>
    </div>
  );
}
